name: Nick
version: '2.0'
main: me.sk8ingduck.nick.Nick
authors: [ sk8ingDuck ]

softdepend:
  - NametagEdit
  - TAB
  - LuckPerms
  - PlaceholderAPI
commands:
  nick:
    description: nick yourself
    usage: /nick